### ISSUE TITLE
No bg for NotifyBackground

### ISSUE THREAD

**Issue by GiyoMoon** [eldritch-theme/eldritch.nvim#4] opened 2024-04-01 18:53 UTC
Hey! I just saw your theme on the neovim subreddit and wanted to give it a try. Looks awesome! 

I got this warning from the `nvim-notify` plugin (only appears after a notification is shown):
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/36984337/b2a6fcc3-1eeb-41d8-848a-c0b74297c269)
I use the default config with `require('eldritch').setup()`. Thanks for your help!

**Comment by jacobrreed** [comment] 2024-04-01 19:12
I'll look into, although ive seen this with other themes as well

**Comment by jacobrreed** [comment] 2024-04-01 19:21
ya interesting ill look at catppucin and everforest, this theme actually forked from tokyonight, and I have the highlight defined for `NotifyBackground` so let me look around and see

**Comment by jacobrreed** [comment] 2024-04-01 19:29
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/25580051/63ffcab7-66ac-49ec-9e97-1e33aef23f0b)
 ya im getting the same thing with catpuccin and tokyonight

**Comment by jacobrreed** [comment] 2024-04-01 19:30
I can add something to the docs for people to add to notify, but im not sure any other way around it, it doesnt seem to respect the NotifyBackground highlight group

**Comment by jacobrreed** [comment] 2024-04-01 19:33
oddly enough if you set the background_colour to any color, my highlight group takes over, it seems like some weird race condition that shoots the notification off, even though colorscheme with priority=1000 will load way before, i'll file an issue and ask in notify's repo

**Comment by jacobrreed** [comment] 2024-04-01 19:38
https://github.com/rcarriga/nvim-notify/issues/264 filed issue here, for now you can set any color in Notify's config using 
```lua
background_color = "#000000"
```

**Comment by GiyoMoon** [comment] 2024-04-01 19:58
interesting. thanks for looking into this!

**Comment by Normanras** [comment] 2024-04-10 21:10
Came here cause I was getting the same issue. What's interesting is in some buffers, when I switch to visual mode, I get no background/highlight color at all. Setting bg to #00000 does indeed trigger Eldritch's red color to begin showing up, but I thought it was strange that I didn't see a bg/highlight color when opening a new buffer.

**Comment by jacobrreed** [comment] 2024-04-10 21:12
> Came here cause I was getting the same issue. What's interesting is in some buffers, when I switch to visual mode, I get no background/highlight color at all. Setting bg to #00000 does indeed trigger Eldritch's red color to begin showing up, but I thought it was strange that I didn't see a bg/highlight color when opening a new buffer. 

Can you screenshot? This seems unrelated to Notify's background color issue unless I'm misunderstanding

**Comment by akthe-at** [comment] 2024-04-11 09:39
I can not reproduce this issue. I am using Neovim Nightly, on Windows OS -- no WSL2, Here is my config to setup Eldritch.nvim:
```
  {
    "eldritch-theme/eldritch.nvim",
    priority = 1000,
    opts = {},
    config = function()
      require("eldritch").setup({
        dim_inactive = true,
        transparent = true,
        hide_inactive_statusline = true,
        lualine_bold = true,
      })
      vim.o.termguicolors = true
    end,
  },
```
Can anyone confirm if this issue still persists with this sort of setup call? @jacobrreed @Normanras @GiyoMoon

**Comment by GiyoMoon** [comment] 2024-04-11 09:46
yes this issue still persists

**Comment by akthe-at** [comment] 2024-04-11 09:54
I am trying to think of other differences...I am using Wezterm Terminal,  I have tried this with and without a background image or background color set in the terminal as well. Do you use any neovim plugins that try to set transparency?

**Comment by GiyoMoon** [comment] 2024-04-11 09:57
I don't think so. I went and disabled all plugins and configurations apart from noice and the theme and it still happens :/

**Comment by jacobrreed** [comment] 2024-04-11 12:56
I tried with tokyonight and same thing happens

**Comment by jacobrreed** [comment] 2024-04-11 20:15
It does seem like it's a race condition, most likely because theme starts up with priority, for me at least, the notify warning shows up but still uses the background like it should. Then any subsequent calls to notify no longer have warning and honor colors, is this the same for everyone else? The workaround here is just setting any color as the `background_colour` option for notify

**Comment by jacobrreed** [comment] 2024-04-29 15:36
Fixed with above merge, thanks @akthe-at

**Closed by jacobrreed** 2024-04-29 15:36 UTC

**Comment by sbmueller** [comment] 2024-06-07 08:23
Hi, the PR resolved the warning for me, but the theme looks wrong.

With transparency = false:
![cmdline_nontransparent](https://github.com/eldritch-theme/eldritch.nvim/assets/7465688/df1a6c5c-26bc-4ebd-979c-ae0c07404b7c)

With transparency = true:
![cmdline_transparent](https://github.com/eldritch-theme/eldritch.nvim/assets/7465688/49418ce3-91a9-4d82-895c-bfdb296981f5)
Note that here all hover GUI elements (Notify.nvim etc.) have a black rectangle background.
